spring.application.name=demo_people
# URL de conexão: localhost na porta 3306, banco todo_db
spring.datasource.url=jdbc:mysql://localhost:3306/register_people_db?useSSL=false&serverTimezone=UTC
# Seu usuário e senha do MySQL
spring.datasource.username=root
spring.datasource.password=Triangulo1!

# O Hibernate cria as tabelas automaticamente baseado nas classes Java
spring.jpa.hibernate.ddl-auto=update
# Mostra no console os comandos SQL que o Spring está executando
spring.jpa.show-sql=true